### PR TITLE
Various fixes

### LINKED ISSUE #135: Hi everyone, i have erorrs on compilation of test, i have boost,openssl,curl but how to add this library currectly ?
Firstly Sorry of my english,
i have this errors:
Ошибка	LNK2019	ссылка на неразрешенный внешний символ "public: static class std::shared_ptr<class TgBot::InputFile> __cdecl TgBot::InputFile::fromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?fromFile@InputFile@TgBot@@SA?AV?$shared_ptr@VInputFile@TgBot@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@0@Z) в функции "public: void __cdecl <lambda_82db6e495dbbaab7ac3df2cf873dfa7e>::operator()(class std::shared_ptr<class TgBot::Message>)const " (??R<lambda_82db6e495dbbaab7ac3df2cf873dfa7e>@@QEBAXV?$shared_ptr@VMessage@TgBot@@@std@@@Z)	testForCPR	C:\Users\acer\source\repos\testForCPR\testForCPR\testForCPR.obj	1

### PR DESCRIPTION
**Pull request by OgreTransporter**
Fix issues:
- #138 
- #137 

Add Generation of API documentation to CMake.

Fix to prevent Boost from linking dynamic and static libraries simultaneously when autolink is enabled. Maybe fix #135.

### CODE REVIEW

File: include/tgbot/export.h [hunk 1]
```diff
@@ -2,7 +2,19 @@
 #define TGBOT_EXPORT_H
 
 #ifndef TGBOT_API
+#ifdef _MSC_VER
```
Comment (egorpugin) [inline include/tgbot/export.h:5]: Please indent lines, add attribute visibility for non windows.

Comment (OgreTransporter) [reply include/tgbot/export.h:5]: ok

File: include/tgbot/export.h [hunk 2]
```diff
@@ -2,7 +2,27 @@
...
+        #else
+            #if __GNUC__ >= 4
+                #define TGBOT_HELPER_DLL_IMPORT __attribute__ ((visibility ("default")))
+                #define TGBOT_HELPER_DLL_EXPORT __attribute__ ((visibility ("default")))
+            #else
+                #define TGBOT_HELPER_DLL_IMPORT
+                #define TGBOT_HELPER_DLL_EXPORT
+            #endif
+        #endif
+        #ifdef TgBot_EXPORTS
```
Comment (egorpugin) [inline include/tgbot/export.h:18]: What is TgBot_EXPORTS?

File: include/tgbot/export.h [hunk 3]
```diff
@@ -2,7 +2,27 @@
...
+            #define TGBOT_API TGBOT_HELPER_DLL_EXPORT
+        #else
+            #define FOX_API TGBOT_HELPER_DLL_IMPORT
```
Comment (egorpugin) [inline include/tgbot/export.h:21]: FOX_API?

File: include/tgbot/export.h [hunk 4]
```diff
@@ -2,7 +2,27 @@
 #define TGBOT_EXPORT_H
 
 #ifndef TGBOT_API
-#define TGBOT_API
+    #ifdef TGBOT_DLL
```
Comment (egorpugin) [inline include/tgbot/export.h:5]: What is TGBOT_DLL? Where is it defined?

**Comment by egorpugin** [comment]
Also reorder export then import, not vice versa.

File: include/tgbot/export.h (hunk 3 above)
Comment (OgreTransporter) [reply include/tgbot/export.h:21]: Ups!

File: include/tgbot/export.h (hunk 2 above)
Comment (OgreTransporter) [reply include/tgbot/export.h:18]: -DTgBot_EXPORTS is automatically added by CMake when the library TgBot is declared as SHARED.

File: include/tgbot/export.h (hunk 4 above)
Comment (OgreTransporter) [reply include/tgbot/export.h:5]: I have defined TGBOT_DLL to differentiate STATIC from SHARED. TgBot_EXPORTS is set by CMake only for export. If TGBOT_DLL is set, it is assumed that the library is SHARED. CMake then sets TgBot_EXPORTS for the export of the DLL functions and classes. If TGBOT_DLL is set and TgBot_EXPORTS is missing, then import is assumed. If TGBOT_DLL is missing, the library is STATIC. You can find the definition in the CMake script.

**Comment by OgreTransporter** [comment]
Thanks for checking the code!

**Comment by egorpugin** [comment]
Thanks for PR!

TGBOT_API was here to provide non-cmake build systems with ability to perform shared builds. with defining all stuff you wrote by them.
Example: https://software-network.org/org.sw.demo.reo7sp.tgbot/specification line 8.
